// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'30d95b14fc28ba41082a0aa72faa7afb9f5fd9f61372ba98887fdb5a60f75387'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Inventory: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly jenis_barang: CodecTypes['pg/text@1']['output'];
      readonly ukuran: CodecTypes['pg/text@1']['output'];
      readonly status: 'inventory' | 'dipinjam';
    };
    readonly Karyawan: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly nama: CodecTypes['pg/text@1']['output'];
      readonly jabatan: CodecTypes['pg/text@1']['output'];
      readonly periode: CodecTypes['pg/text@1']['output'];
      readonly status_kerja: 'active' | 'inactive';
    };
    readonly Peminjaman: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly karyawan_id: CodecTypes['pg/int4@1']['output'];
      readonly inventory_id: CodecTypes['pg/int4@1']['output'];
      readonly tanggal_peminjaman: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly Pengembalian: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly peminjaman_id: CodecTypes['pg/int4@1']['output'];
      readonly tanggal_pengembalian: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Inventory: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly jenis_barang: CodecTypes['pg/text@1']['input'];
      readonly ukuran: CodecTypes['pg/text@1']['input'];
      readonly status: 'inventory' | 'dipinjam';
    };
    readonly Karyawan: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly nama: CodecTypes['pg/text@1']['input'];
      readonly jabatan: CodecTypes['pg/text@1']['input'];
      readonly periode: CodecTypes['pg/text@1']['input'];
      readonly status_kerja: 'active' | 'inactive';
    };
    readonly Peminjaman: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly karyawan_id: CodecTypes['pg/int4@1']['input'];
      readonly inventory_id: CodecTypes['pg/int4@1']['input'];
      readonly tanggal_peminjaman: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly Pengembalian: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly peminjaman_id: CodecTypes['pg/int4@1']['input'];
      readonly tanggal_pengembalian: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly inventory: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly jenis_barang: CodecTypes['pg/text@1']['output'];
      readonly status: 'inventory' | 'dipinjam';
      readonly ukuran: CodecTypes['pg/text@1']['output'];
    };
    readonly karyawan: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly jabatan: CodecTypes['pg/text@1']['output'];
      readonly nama: CodecTypes['pg/text@1']['output'];
      readonly periode: CodecTypes['pg/text@1']['output'];
      readonly status_kerja: 'active' | 'inactive';
    };
    readonly peminjaman: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly inventory_id: CodecTypes['pg/int4@1']['output'];
      readonly karyawan_id: CodecTypes['pg/int4@1']['output'];
      readonly tanggal_peminjaman: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly pengembalian: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly peminjaman_id: CodecTypes['pg/int4@1']['output'];
      readonly tanggal_pengembalian: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly inventory: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly jenis_barang: CodecTypes['pg/text@1']['input'];
      readonly status: 'inventory' | 'dipinjam';
      readonly ukuran: CodecTypes['pg/text@1']['input'];
    };
    readonly karyawan: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly jabatan: CodecTypes['pg/text@1']['input'];
      readonly nama: CodecTypes['pg/text@1']['input'];
      readonly periode: CodecTypes['pg/text@1']['input'];
      readonly status_kerja: 'active' | 'inactive';
    };
    readonly peminjaman: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly inventory_id: CodecTypes['pg/int4@1']['input'];
      readonly karyawan_id: CodecTypes['pg/int4@1']['input'];
      readonly tanggal_peminjaman: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly pengembalian: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly peminjaman_id: CodecTypes['pg/int4@1']['input'];
      readonly tanggal_pengembalian: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
  };
};

export namespace Models {
  export type public_Inventory = {
    id: CodecTypes['pg/int4@1']['output'];
    jenis_barang: CodecTypes['pg/text@1']['output'];
    ukuran: CodecTypes['pg/text@1']['output'];
    status: 'inventory' | 'dipinjam';
    Peminjaman: public_Peminjaman[];
    readonly [RelationKeys]?: 'Peminjaman';
  };
  export type public_Karyawan = {
    id: CodecTypes['pg/int4@1']['output'];
    nama: CodecTypes['pg/text@1']['output'];
    jabatan: CodecTypes['pg/text@1']['output'];
    periode: CodecTypes['pg/text@1']['output'];
    status_kerja: 'active' | 'inactive';
    Peminjaman: public_Peminjaman[];
    readonly [RelationKeys]?: 'Peminjaman';
  };
  export type public_Peminjaman = {
    id: CodecTypes['pg/int4@1']['output'];
    karyawan_id: CodecTypes['pg/int4@1']['output'];
    inventory_id: CodecTypes['pg/int4@1']['output'];
    tanggal_peminjaman: CodecTypes['pg/timestamptz-temporal@1']['output'];
    Pengembalian: public_Pengembalian | null;
    inventory: public_Inventory;
    karyawan: public_Karyawan;
    readonly [RelationKeys]?: 'Pengembalian' | 'inventory' | 'karyawan';
  };
  export type public_Pengembalian = {
    id: CodecTypes['pg/int4@1']['output'];
    peminjaman_id: CodecTypes['pg/int4@1']['output'];
    tanggal_pengembalian: CodecTypes['pg/timestamptz-temporal@1']['output'];
    peminjaman: public_Peminjaman;
    readonly [RelationKeys]?: 'peminjaman';
  };
}

export declare const models: {
  public: {
    Inventory: Models.public_Inventory;
    Karyawan: Models.public_Karyawan;
    Peminjaman: Models.public_Peminjaman;
    Pengembalian: Models.public_Pengembalian;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly inventory: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly jenis_barang: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly ukuran: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly karyawan: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly nama: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly jabatan: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly periode: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly status_kerja: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly peminjaman: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly karyawan_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly inventory_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly tanggal_peminjaman: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'peminjaman_karyawan_id_idx_f515877e';
                  readonly prefix: 'peminjaman_karyawan_id_idx';
                  readonly columns: readonly ['karyawan_id'];
                  readonly unique: false;
                },
                {
                  readonly name: 'peminjaman_inventory_id_idx_d5937af2';
                  readonly prefix: 'peminjaman_inventory_id_idx';
                  readonly columns: readonly ['inventory_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'peminjaman';
                    readonly columns: readonly ['karyawan_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'karyawan';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'peminjaman';
                    readonly columns: readonly ['inventory_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'inventory';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly pengembalian: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly peminjaman_id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly tanggal_pengembalian: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['peminjaman_id'] }];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'pengembalian';
                    readonly columns: readonly ['peminjaman_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'peminjaman';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
          };
          readonly valueSet: {
            readonly StatusInventory: {
              readonly kind: 'valueSet';
              readonly values: readonly ['inventory', 'dipinjam'];
            };
            readonly StatusKerja: {
              readonly kind: 'valueSet';
              readonly values: readonly ['active', 'inactive'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly inventory: { readonly namespace: 'public' & NamespaceId; readonly model: 'Inventory' };
    readonly karyawan: { readonly namespace: 'public' & NamespaceId; readonly model: 'Karyawan' };
    readonly peminjaman: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Peminjaman';
    };
    readonly pengembalian: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Pengembalian';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Inventory: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly jenis_barang: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly ukuran: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly Peminjaman: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Peminjaman';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['inventory_id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'inventory';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly jenis_barang: { readonly column: 'jenis_barang' };
                readonly ukuran: { readonly column: 'ukuran' };
                readonly status: { readonly column: 'status' };
              };
            };
          };
          readonly Karyawan: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly nama: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly jabatan: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly periode: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly status_kerja: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly Peminjaman: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Peminjaman';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['karyawan_id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'karyawan';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly nama: { readonly column: 'nama' };
                readonly jabatan: { readonly column: 'jabatan' };
                readonly periode: { readonly column: 'periode' };
                readonly status_kerja: { readonly column: 'status_kerja' };
              };
            };
          };
          readonly Peminjaman: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly karyawan_id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly inventory_id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly tanggal_peminjaman: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly Pengembalian: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Pengembalian';
                };
                readonly cardinality: '1:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['peminjaman_id'];
                };
              };
              readonly inventory: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Inventory';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['inventory_id'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly karyawan: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Karyawan';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['karyawan_id'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'peminjaman';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly karyawan_id: { readonly column: 'karyawan_id' };
                readonly inventory_id: { readonly column: 'inventory_id' };
                readonly tanggal_peminjaman: { readonly column: 'tanggal_peminjaman' };
              };
            };
          };
          readonly Pengembalian: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly peminjaman_id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly tanggal_pengembalian: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly peminjaman: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Peminjaman';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['peminjaman_id'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'pengembalian';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly peminjaman_id: { readonly column: 'peminjaman_id' };
                readonly tanggal_pengembalian: { readonly column: 'tanggal_pengembalian' };
              };
            };
          };
        };
        readonly enum: {
          readonly StatusInventory: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'inventory'; readonly value: 'inventory' },
              { readonly name: 'dipinjam'; readonly value: 'dipinjam' },
            ];
          };
          readonly StatusKerja: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'active'; readonly value: 'active' },
              { readonly name: 'inactive'; readonly value: 'inactive' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
